import type { StrapiImage } from "@/types/strapi";

export const createMockStrapiImage = (overrides?: Partial<StrapiImage>): StrapiImage => ({
  id: 1,
  documentId: "img-1",
  name: "test-image.jpg",
  alternativeText: "Test image",
  caption: "Test caption",
  width: 1200,
  height: 800,
  formats: {
    thumbnail: {
      name: "thumbnail_test-image.jpg",
      hash: "thumbnail_hash",
      ext: ".jpg",
      mime: "image/jpeg",
      width: 156,
      height: 156,
      size: 5.5,
      url: "/uploads/thumbnail_hash.jpg",
    },
    small: {
      name: "small_test-image.jpg",
      hash: "small_hash",
      ext: ".jpg",
      mime: "image/jpeg",
      width: 500,
      height: 333,
      size: 25.3,
      url: "/uploads/small_hash.jpg",
    },
  },
  hash: "main_hash",
  ext: ".jpg",
  mime: "image/jpeg",
  size: 125.5,
  url: "/uploads/main_hash.jpg",
  previewUrl: undefined,
  provider: "local",
  provider_metadata: undefined,
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: "2024-01-01T00:00:00.000Z",
  publishedAt: "2024-01-01T00:00:00.000Z",
  ...overrides,
});
